In [1]:
# Dependencies and Setup
from pathlib import Path
import pandas as pd
EV_final_path = Path("Final_Resource/EV_final.csv")
EV_final_df = pd.read_csv(EV_final_path)
EV_final_df.head()

,State,Registrations of EV 2019,Registrations of EV 2020,Registrations of EV 2021,Total EV,YOY(2020-2021)Growth Percentage,2019 - No. EV charge outlets,2020 - No. EV charge outlets,2021 - No. EV charge outlets,Total charging outlets,EV:Charger outlets,Average fuel price(current),Capital,ST,Lat,Lon
0,Alabama,722,2890.0,4750.0,8362.0,64.40%,506.0,596.0,680.0,1782.0,4.69,$3.08,Montgomery,AL,32.366966,-86.300648
1,Alaska,87,940.0,1290.0,2317.0,37.23%,34.0,45.0,94.0,173.0,13.39,$4.31,Juneau,AK,58.301950,-134.419734
2,Arizona,6637,28770.0,40740.0,76147.0,41.61%,1476.0,1778.0,2257.0,5511.0,13.82,$3.79,Phoenix,AZ,33.448437,-112.074141
3,Arkansas,370,1330.0,2390.0,4090.0,79.70%,290.0,350.0,453.0,1093.0,3.74,$3.09,Little Rock,AR,34.746507,-92.289627
4,California,100549,425300.0,563070.0,1088919.0,32.40%,27128.0,34622.0,41225.0,102975.0,10.57,$4.87,Sacramento,CA,38.581061,-121.493895

In [2]:
#Top 5 States with most ev registered
EV_final_df.sort_values("Total EV", ascending= False).head()

,State,Registrations of EV 2019,Registrations of EV 2020,Registrations of EV 2021,Total EV,YOY(2020-2021)Growth Percentage,2019 - No. EV charge outlets,2020 - No. EV charge outlets,2021 - No. EV charge outlets,Total charging outlets,EV:Charger outlets,Average fuel price(current),Capital,ST,Lat,Lon
4,California,100549,425300.0,563070.0,1088919.0,32.40%,27128.0,34622.0,41225.0,102975.0,10.57,$4.87,Sacramento,CA,38.581061,-121.493895
8,Florida,13137,58160.0,95640.0,166937.0,64.44%,4562.0,5519.0,6723.0,16804.0,9.93,$3.46,Tallahassee,FL,30.438083,-84.280933
42,Texas,3460,52190.0,80900.0,136550.0,55.01%,4009.0,4802.0,5486.0,14297.0,9.55,$3.16,Austin,TX,30.271129,-97.743700
46,Washington,10256,50520.0,66810.0,127586.0,32.30%,3206.0,3771.0,4328.0,11305.0,11.29,$4.96,Olympia,WA,47.045102,-122.895008
31,New York,8830,32590.0,51870.0,93290.0,59.16%,4531.0,6092.0,7621.0,18244.0,5.11,$3.68,Albany,NY,42.651167,-73.754968

In [3]:
#top 5 states with highest percentage growth  in sales between year 2020-2021)
new_values=EV_final_df["YOY(2020-2021)Growth Percentage"].str.strip("%").astype(float)
EV_final_df["YOY(2020-2021)Growth Percentage"]=new_values
EV_final_df.sort_values(by = "YOY(2020-2021)Growth Percentage",ascending = False).head()

,State,Registrations of EV 2019,Registrations of EV 2020,Registrations of EV 2021,Total EV,YOY(2020-2021)Growth Percentage,2019 - No. EV charge outlets,2020 - No. EV charge outlets,2021 - No. EV charge outlets,Total charging outlets,EV:Charger outlets,Average fuel price(current),Capital,ST,Lat,Lon
35,Oklahoma,551,3410.0,7180.0,11141.0,111.00,309.0,693.0,1088.0,2090.0,5.33,$3.16,Oklahoma City,OK,35.472989,-97.517054
3,Arkansas,370,1330.0,2390.0,4090.0,79.70,290.0,350.0,453.0,1093.0,3.74,$3.09,Little Rock,AR,34.746507,-92.289627
25,Montana,230,940.0,1650.0,2820.0,75.53,137.0,188.0,212.0,537.0,5.25,$3.72,Helena,MT,46.592742,-112.036277
33,North Dakota,92,220.0,380.0,692.0,72.73,46.0,101.0,139.0,286.0,2.42,$3.46,Bismarck,ND,46.808327,-100.783739
39,South Carolina,956,4390.0,7440.0,12786.0,69.50,643.0,727.0,862.0,2232.0,5.73,$3.17,Columbia,SC,34.000749,-81.034331

In [4]:
#top 5 states with the highest number of charging outlets
EV_final_df.sort_values(by = "Total charging outlets",ascending = False).head()

,State,Registrations of EV 2019,Registrations of EV 2020,Registrations of EV 2021,Total EV,YOY(2020-2021)Growth Percentage,2019 - No. EV charge outlets,2020 - No. EV charge outlets,2021 - No. EV charge outlets,Total charging outlets,EV:Charger outlets,Average fuel price(current),Capital,ST,Lat,Lon
4,California,100549,425300.0,563070.0,1088919.0,32.40,27128.0,34622.0,41225.0,102975.0,10.57,$4.87,Sacramento,CA,38.581061,-121.493895
31,New York,8830,32590.0,51870.0,93290.0,59.16,4531.0,6092.0,7621.0,18244.0,5.11,$3.68,Albany,NY,42.651167,-73.754968
8,Florida,13137,58160.0,95640.0,166937.0,64.44,4562.0,5519.0,6723.0,16804.0,9.93,$3.46,Tallahassee,FL,30.438083,-84.280933
42,Texas,3460,52190.0,80900.0,136550.0,55.01,4009.0,4802.0,5486.0,14297.0,9.55,$3.16,Austin,TX,30.271129,-97.743700
46,Washington,10256,50520.0,66810.0,127586.0,32.30,3206.0,3771.0,4328.0,11305.0,11.29,$4.96,Olympia,WA,47.045102,-122.895008

In [5]:
#top 5 states with the best Electric vehicles to charger ports ratio
EV_final_df.sort_values(by = "EV:Charger outlets",ascending = False).head()

,State,Registrations of EV 2019,Registrations of EV 2020,Registrations of EV 2021,Total EV,YOY(2020-2021)Growth Percentage,2019 - No. EV charge outlets,2020 - No. EV charge outlets,2021 - No. EV charge outlets,Total charging outlets,EV:Charger outlets,Average fuel price(current),Capital,ST,Lat,Lon
29,New Jersey,7276,30420.0,47830.0,85526.0,57.23,1297.0,1651.0,2008.0,4956.0,17.26,$3.52,Trenton,NJ,40.220594,-74.759722
2,Arizona,6637,28770.0,40740.0,76147.0,41.61,1476.0,1778.0,2257.0,5511.0,13.82,$3.79,Phoenix,AZ,33.448437,-112.074141
1,Alaska,87,940.0,1290.0,2317.0,37.23,34.0,45.0,94.0,173.0,13.39,$4.31,Juneau,AK,58.301950,-134.419734
10,Hawaii,2488,10670.0,14220.0,27378.0,33.30,666.0,760.0,833.0,2259.0,12.12,$4.69,Honolulu,HI,21.304547,-157.855676
46,Washington,10256,50520.0,66810.0,127586.0,32.30,3206.0,3771.0,4328.0,11305.0,11.29,$4.96,Olympia,WA,47.045102,-122.895008